token: "MTI0OTI1ODk2NjIzMjQ2OTUwNg.GYaQBy.cEAVh6kDviqcr-CRy2M3yGe9tV7o7ZXSOb1l2Y"
guild_id: "1170748791616450652"

staff_roles:
  - "1170748791616450660"

ticket_category_id: "1170748792660820094"
feedback_channel_id: "1170748792660820095"
transcript_channel_id: "1170748792660820095"

embed_color: "#5865F2"
footer_text: "Support System Â© 2025"
blacklist_message: "âŒ You are blacklisted from creating tickets."
close_ticket_message: "âœ… Ticket closed by {user}."
ticket_created_message: "ğŸ« Your ticket has been created!"
feedback_prompt_message: "â­ Please rate your support experience!"
